# Generated by Django 6.0.7 on 2026-07-27 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_streak_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
